{% set name = "pylexique" %}

{% set version = "1.5.1" %}



package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pylexique-{{ version }}.tar.gz
  sha256: e2173c2b4dd444548c4f2717fee7961814d15bf9ef3f308011284adba09b781b

build:
  number: 0
  entry_points:
    - pylexique=pylexique.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.7
    - poetry
  run:
    - python >=3.7
    - setuptools
    - dataclasses
    - pandas
    - click >=8.0.3

test:
  imports:
    - pylexique
  commands:
    - pylexique --help
  requires:
    - pip
    - poetry

about:
  description: |
    Pylexique is a Python wrapper around Lexique383.
    It allows to extract lexical information from more than 140 000 French words in an Object Oriented way.

    Features:

      - Extract all lexical information from a French word such as
          - orthographic and phonemics representations
          - associated lemmas
          - syllabation
          - grammatical category
          - gender and number
          - frequencies in a corpus of books and in a body of film subtitles, etc…
      - Get all related words to a given word.
      - Easy to use Api.
      - Easily integrate pylexique in your own projects as an imported library.
      - Can be used as a command line tool.
  home: https://github.com/SekouDiaoNlp/pylexique
  summary: Pylexique is a Python wrapper around Lexique383
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - SekouDiaoNlp
